version: '3.8'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: openmsp-vaultwarden
    restart: unless-stopped
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=true
    volumes:
      - ./data:/data
    ports:
      - "8080:80"
      - "3012:3012"
