import React, { useState } from 'react';
import { useApp } from '../../data/AppContext';
import {
  Bot,
  Sparkles,
  Terminal,
  Play,
  Copy,
  Check,
  FileText,
  Send,
  Zap,
  Activity,
  ShieldCheck
} from 'lucide-react';

export const AICopilotView: React.FC = () => {
  const { aiMessages, sendAIMessage, devices, tickets, patches } = useApp();
  const [promptText, setPromptText] = useState('');
  const [qbrReport, setQbrReport] = useState<string | null>(null);
  const [copiedQbr, setCopiedQbr] = useState(false);

  const handleGenerateQBR = () => {
    const report = `# ApexMSP Quarterly Executive Business Review (QBR)
Client: Apex Financial Technologies
Date: ${new Date().toLocaleDateString()}

## Executive Infrastructure Summary
- Total Endpoints Monitored: ${devices.length} Devices
- Average Fleet Health Score: 98.2%
- Self-Healing Automations Triggered: 61 Events (100% Autonomous Remediation)
- OS Patch Compliance Level: 92.4%
- Zero-Trust Bitwarden Security Score: 95.8/100

## SLA & Support Metrics
- Total PSA Tickets Handled: ${tickets.length}
- Average First Response Time: 4.2 Minutes
- SLA Breach Percentage: 0.0%

## AI & Cyber Defense Assessment
- RustDesk Encrypted Tunnels Established: Active 24/7
- Zero-Trust 2FA Enforcement: 100% Compliant across all endpoints.

Generated by Apex AI Copilot.`;

    setQbrReport(report);
  };

  const handleSubmitPrompt = (e: React.FormEvent) => {
    e.preventDefault();
    if (!promptText.trim()) return;
    sendAIMessage(promptText);
    setPromptText('');
  };

  return (
    <div className="flex-1 p-6 overflow-y-auto custom-scrollbar bg-slate-950 text-slate-100 space-y-6">
      {/* Header */}
      <div className="p-6 rounded-2xl bg-gradient-to-r from-slate-900 via-slate-900 to-indigo-950 border border-slate-800 flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="p-3 rounded-2xl bg-indigo-500/10 text-indigo-400">
            <Bot className="w-6 h-6" />
          </div>
          <div>
            <h1 className="text-xl font-bold text-white">Apex AI Workbench & Script Synthesizer</h1>
            <p className="text-slate-400 text-xs">AI-driven ticket resolution, natural language PowerShell/Bash script synthesis, and automated QBR reports</p>
          </div>
        </div>

        <button
          onClick={handleGenerateQBR}
          className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-extrabold text-xs transition shadow-lg shadow-indigo-600/30"
        >
          <FileText className="w-4 h-4" />
          <span>Generate Client QBR Report</span>
        </button>
      </div>

      {/* Main Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left: Interactive Prompt & Script Synthesis */}
        <div className="p-5 rounded-2xl bg-slate-900 border border-slate-800 flex flex-col h-[550px]">
          <div className="flex items-center gap-2 pb-3 border-b border-slate-800 text-xs font-bold text-slate-300">
            <Sparkles className="w-4 h-4 text-sky-400" />
            <span>Interactive Script Synthesizer</span>
          </div>

          <div className="flex-1 p-4 overflow-y-auto custom-scrollbar space-y-4 my-3 bg-slate-950 rounded-xl border border-slate-800/80">
            {aiMessages.map(msg => (
              <div key={msg.id} className="space-y-1">
                <div className="text-[10px] text-slate-500 font-bold">{msg.sender === 'user' ? 'Technician Prompt' : 'Apex AI Model'}</div>
                <div className={`p-3 rounded-xl text-xs ${msg.sender === 'user' ? 'bg-sky-600 text-white' : 'bg-slate-900 text-slate-200 border border-slate-800'}`}>
                  {msg.text}
                  {msg.codeSnippet && (
                    <pre className="mt-2 p-2 rounded bg-black text-sky-400 font-mono text-[11px] overflow-x-auto whitespace-pre">
                      {msg.codeSnippet}
                    </pre>
                  )}
                </div>
              </div>
            ))}
          </div>

          <form onSubmit={handleSubmitPrompt} className="flex items-center gap-2">
            <input
              type="text"
              value={promptText}
              onChange={(e) => setPromptText(e.target.value)}
              placeholder="Describe what script or diagnostic you need..."
              className="flex-1 p-3 rounded-xl bg-slate-950 border border-slate-800 text-slate-100 text-xs outline-none focus:border-indigo-500"
            />
            <button type="submit" className="px-4 py-3 rounded-xl bg-sky-600 hover:bg-sky-500 text-white font-bold text-xs flex items-center gap-1.5">
              <Send className="w-4 h-4" /> Generate
            </button>
          </form>
        </div>

        {/* Right: Generated Executive QBR Report */}
        <div className="p-5 rounded-2xl bg-slate-900 border border-slate-800 flex flex-col h-[550px]">
          <div className="flex items-center justify-between pb-3 border-b border-slate-800">
            <div className="flex items-center gap-2 text-xs font-bold text-slate-300">
              <FileText className="w-4 h-4 text-amber-400" />
              <span>Automated QBR Report Viewer</span>
            </div>
            {qbrReport && (
              <button
                onClick={() => {
                  navigator.clipboard.writeText(qbrReport);
                  setCopiedQbr(true);
                  setTimeout(() => setCopiedQbr(false), 2000);
                }}
                className="px-3 py-1 rounded bg-slate-800 text-slate-200 text-xs font-bold flex items-center gap-1"
              >
                {copiedQbr ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedQbr ? 'Copied' : 'Copy Report'}</span>
              </button>
            )}
          </div>

          <div className="flex-1 p-4 overflow-y-auto custom-scrollbar my-3 bg-slate-950 rounded-xl border border-slate-800/80 font-mono text-xs text-sky-300 whitespace-pre-wrap leading-relaxed">
            {qbrReport || 'Click "Generate Client QBR Report" above to compile an executive PDF/Markdown digest for client Quarterly Business Reviews.'}
          </div>
        </div>
      </div>
    </div>
  );
};
